---
driver: 
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.7
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.0

suites:
  - name: monit-ng-default
    run_list:
      - recipe[setup]
  - name: monit-ng-source
    run_list:
      - recipe[setup]
    attributes:
      monit:
        install_method: source
