---
driver: 
  name: bluebox

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-12.04
  driver_config:
    image_id: 73a7ceb3-d9a8-419e-9529-7c11c0392ab5
- name: centos-6.5
  driver_config:
    image_id: 69ddc02e-7e29-48a5-9284-3d4f4b7f3e98

settings:
  parallel: true
  destroy: always

suites:
- name: monit-default
  run_list:
  - recipe[setup]
  - recipe[monit::default]
  - recipe[monit::sshd]
  - recipe[monit::crond]
  attributes: {}
- name: monit-source
  run_list:
  - recipe[setup]
  - recipe[monit::default]
  - recipe[monit::sshd]
  - recipe[monit::crond]
  attributes: { monit: { install_method: 'source' } }
