---
driver: 
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5
  - name: centos-7.0

settings:
  parallel: true
  destroy: always

suites:
  - name: monit-ng-default
    run_list:
      - recipe[setup]
      - recipe[monit-ng::default]
      - recipe[monit-ng::sshd]
      - recipe[monit-ng::crond]
      - recipe[monit-ng::rootfs]
    attributes: {}
  - name: monit-ng-source
    run_list:
      - recipe[setup]
      - recipe[monit-ng::default]
      - recipe[monit-ng::sshd]
      - recipe[monit-ng::crond]
      - recipe[monit-ng::rootfs]
    attributes: { monit: { install_method: 'source' } }
