---
driver_plugin: bluebox

driver_config:
  bluebox_customer_id: <%= ENV['BLUEBOX_CUSTOMER_ID'] %>
  bluebox_api_key: <%= ENV['BLUEBOX_API_KEY'] %>
  ssh_public_key: <%= "#{ENV['HOME']}/.ssh/id_rsa.pub" %>
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    image_id: 90cb3e60-73ba-4bbd-a3aa-19e8bd1e1db0
- name: centos-6.5
  driver_config:
    image_id: 6856aaa1-4dc0-4d01-a2d4-aa9e42aba5bb

settings:
  parallel: true
  destroy: always

suites:
- name: default
  run_list: 
  - recipe[monit]
  attributes: {}
- name: source
  run_list:
  - recipe[monit]
  attributes: { monit: { install_method: "source" } }
