---
driver_plugin: bluebox
driver_config:
  bluebox_customer_id: <%= ENV['BLUEBOX_CUSTOMER_ID'] %>
  bluebox_api_key: <%= ENV['BLUEBOX_API_KEY'] %>
  ssh_public_key: <%= File.expand_path('~/.ssh/id_rsa.pub') %>
  ssh_key: <%= File.expand_path('~/.ssh/id_rsa')
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    image_id: ca245cf0-9d11-4178-b111-3715f79877ae
- name: scientific-6.4
  driver_config:
    image_id: b21c33d2-b76a-4ce4-a18b-af5911045f42

suites:
- name: monit_default
  run_list: 
  - recipe[monit]
  attributes: {}
- name: monit_source
  run_list:
  - recipe[monit]
  attributes: { monit: { install_method: "source" } }
