---
driver: 
  name: bluebox

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-12.04
  driver_config:
    image_id: 90cb3e60-73ba-4bbd-a3aa-19e8bd1e1db0
- name: centos-6.5
  driver_config:
    image_id: 6856aaa1-4dc0-4d01-a2d4-aa9e42aba5bb

settings:
  parallel: true
  destroy: always

suites:
- name: monit-default
  run_list:
  - recipe[monit::default]
  - recipe[monit::sshd]
  attributes: {}
- name: monit-source
  run_list:
  - recipe[monit::default]
  - recipe[monit::sshd]
  attributes: { monit: { install_method: 'source' } }
