---
driver: 
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
- name: centos-6.5

settings:
  parallel: true
  destroy: always

suites:
- name: monit-default
  run_list:
  - recipe[setup]
  - recipe[monit::default]
  - recipe[monit::sshd]
  - recipe[monit::crond]
  - recipe[monit::rootfs]
  attributes: {}
- name: monit-source
  run_list:
  - recipe[setup]
  - recipe[monit::default]
  - recipe[monit::sshd]
  - recipe[monit::crond]
  - recipe[monit::rootfs]
  attributes: { monit: { install_method: 'source' } }
