AllCops:
  Exclude:
    - Berksfile
    - Rakefile
    - metadata.rb
    - vendor/**/*
    - spec/**/*
    - test/**/*
Documentation:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
BlockLength:
  Enabled: false
